INSERT INTO books(book_name,author_name,key_takeaways) VALUES ('The Alchemist','Paulo Coelho','Listen to your heart if you want your dreams to come true.');
INSERT INTO books(book_name,author_name,key_takeaways) VALUES ('Atomic Habits','James Clear','Every time we perform a habit- we execute a four-step pattern: cue- craving- response- reward.');
INSERT INTO books(book_name,author_name,key_takeaways) VALUES ('Thinking Fast And Slow','Daniel Kahneman','The biggest leaps in progress are vertical- not horizontal.');
INSERT INTO books(book_name,author_name,key_takeaways) VALUES ('The Four Agreements','Don Miguel Ruiz','Were domesticated from a young age and it leaves us living by a set of rules we havent chosen ourselves.');
INSERT INTO books(book_name,author_name,key_takeaways) VALUES ('The 7 Habits Of Highly Effective People','Stephen R Covey','Do the funeral test.');
INSERT INTO books(book_name,author_name,key_takeaways) VALUES ('Best Self','Mike Bayer','Dont worry if you never learned how to reach your full potential- simply start now by defining the version of yourself that would make you happiest.');
INSERT INTO books(book_name,author_name,key_takeaways) VALUES ('The Subtle Art of Not Giving a Fck','Mark Manson','Values you cant control are bad values to follow.');
INSERT INTO books(book_name,author_name,key_takeaways) VALUES ('Girl Wash Your Face','Rachel Hollis','Build the habit of keeping your promises to yourself because breaking them pulls you down.');
INSERT INTO books(book_name,author_name,key_takeaways) VALUES ('You Are A Badass','Jen Sincero','Decide youll stop caring what other people think. Right. now.');
INSERT INTO books(book_name,author_name,key_takeaways) VALUES ('12 Rules For Life','Jordan Peterson','Sweep in front of your own door before pointing out the street is dirty.');
INSERT INTO books(book_name,author_name,key_takeaways) VALUES ('The 48 Laws Of Power','Robert Greene','Always make superiors look smarter than you.');
INSERT INTO books(book_name,author_name,key_takeaways) VALUES ('The Courage To Be Disliked','Ichiro Kishimi Fumitake Koga','Its dangerous to believe that your past determines your future.');
INSERT INTO books(book_name,author_name,key_takeaways) VALUES ('Mans Search For Meaning','Viktor Frankl','Sometimes the only way to survive is to surrender to death..');
INSERT INTO books(book_name,author_name,key_takeaways) VALUES ('How To Stop Worrying And Start Living','Dale Carnegie','Use a 3-step approach to deal with confusion and youll eliminate the worry caused by it.');
INSERT INTO books(book_name,author_name,key_takeaways) VALUES ('Daring Greatly','Brene Brown','Vulnerability means strength- not weakness.');
INSERT INTO books(book_name,author_name,key_takeaways) VALUES ('Big Magic','Elizabeth Gilbert','Let your fears coexist with your passions.');
INSERT INTO books(book_name,author_name,key_takeaways) VALUES ('Quiet','Susan Cain','Whether you like small talk or not is part of your personality type.');
INSERT INTO books(book_name,author_name,key_takeaways) VALUES ('The Magic Of Thinking Big','David Joseph Schwartz','Always be open to new ideas.');
INSERT INTO books(book_name,author_name,key_takeaways) VALUES ('How To Win Friends And Influence People','Dale Carnegie','You can make a great first impression just by smiling.');
INSERT INTO books(book_name,author_name,key_takeaways) VALUES ('The 5 Love Languages','Gary Chapman','As your relationship matures- communication is key.');
INSERT INTO books(book_name,author_name,key_takeaways) VALUES ('Deep Work','Cal Newport','There are four strategies for deep work- all of which require intention.');
INSERT INTO books(book_name,author_name,key_takeaways) VALUES ('Getting Things Done','David Allen','Use a collection bucket to store things outside your mind and stay focused.');
INSERT INTO books(book_name,author_name,key_takeaways) VALUES ('Who Moved My Cheese','Spencer Johnson','Thinking too much about your cheese might paralyze you- so just start looking.');
INSERT INTO books(book_name,author_name,key_takeaways) VALUES ('Rich Dad Poor Dad','Robert T Kiyosaki','Get a real financial education if you ever want to exit the rat race and stop living paycheck to paycheck.');
INSERT INTO books(book_name,author_name,key_takeaways) VALUES ('Think And Grow Rich','Napoleon Hill','Use autosuggestion to build an unshakable belief in yourself.');
INSERT INTO books(book_name,author_name,key_takeaways) VALUES ('The 4-Hour Workweek','Tim Ferriss','Be effective- not efficient.');
INSERT INTO books(book_name,author_name,key_takeaways) VALUES ('Outliers','Malcolm Gladwell','After you cross a certain skill threshold- your abilities wont help you.');
INSERT INTO books(book_name,author_name,key_takeaways) VALUES ('The Power Of Positive Thinking','Norman Vincent Peale','Start with confidence and watch your problems shrink.');
INSERT INTO books(book_name,author_name,key_takeaways) VALUES ('The Secret','Rhonda Byrne','The law of attraction is one of the most prevalent principles in the world.');
INSERT INTO books(book_name,author_name,key_takeaways) VALUES ('Meditations','Marcus Aurelius','Logic doesnt always make sense- but everything happens for a reason.');
INSERT INTO books(book_name,author_name,key_takeaways) VALUES ('The Obstacle Is The Way','Ryan Holiday','Imagine youre advising yourself as a friend to keep an objective perspective.');
INSERT INTO books(book_name,author_name,key_takeaways) VALUES ('The Power Of Now','Eckhart Tolle','Life is just a series of present moments.');
INSERT INTO books(book_name,author_name,key_takeaways) VALUES ('The Life-Changing Magic Of Tidying Up','Marie Kondo','Move from easy to hard items when considering what to keep.');
